## Laboratorio 4

Juan Ivan Cubillos Garay


Karen Natalia Polania Arias

# Primero punto

In [32]:
#Punto A

import itertools as it
import numpy as np
import time
from scipy.optimize import linprog
A1=[[1,1,1,1,1],[1,2,3,4,5],[4,3,3,3,4]]
A2=[[1,1,1,1,1],[1,2,3,4,5],[2,3,4,5,6]]
A1=np.array(A1)
A2=np.array(A2)
B=[1,2,3]
def solucionesbasicas(A,B):
  lenb = len(B)
  solucionesbasica = []
  i = 0
  m = len(A)
  n = len(A[0])
  comb = it.combinations(range(n),lenb)
  comb = list(comb)
  d = len(comb)
  i = 0
  base=[]
  MA=[]
  while i<d:
    Matriz = []
    j = 0
    k = 0
    while k<lenb:
      Matriz.append([])
      k+=1
    while j<lenb:
      a = comb[i][j]
      k = 0
      while k<lenb:
        Matriz[k].append(A[k][a])
        k+= 1
      j+=1
      MA.append(list(A[:,a]))
    MA=np.transpose(MA)
    determinante=np.linalg.det(Matriz)
    if determinante!=0:
      sol = np.linalg.solve(np.array(Matriz),np.array(B))
      solucionesbasica.append(list(sol))
    else:
      solucionesbasica.append('La Matriz base es singular')
    base.append(list(MA))
    MA=[]
    i+=1
  dir={'Solucion': solucionesbasica,'Base': base}
  return dir

In [8]:
#Punto B y C

import pandas as pd
from IPython.display import display

pd.set_option('max_colwidth',75)

SolBasRC=solucionesbasicas(A1,B)
SolBasRD=solucionesbasicas(A2,B)

df_SolBasRC=pd.DataFrame(SolBasRC)
print('\n Matriz de rango completo: \n')
display(df_SolBasRC)

print('\n Matriz de rango deficiente): \n')
display(pd.DataFrame(SolBasRD))

 Matriz de rango completo:

,Solucion,Base
0,"[0.0, 1.0, -0.0]","[[1, 1, 1], [1, 2, 3], [4, 3, 3]]"
1,"[0.0, 1.0, -0.0]","[[1, 1, 1], [1, 2, 4], [4, 3, 3]]"
2,"[0.0, 1.0, -0.0]","[[1, 1, 1], [1, 2, 5], [4, 3, 4]]"
3,"[2.220446049250313e-16, 1.9999999999999991, -0.9999999999999996]","[[1, 1, 1], [1, 3, 4], [4, 3, 3]]"
4,"[0.25, 1.0, -0.25]","[[1, 1, 1], [1, 3, 5], [4, 3, 4]]"
5,"[0.5, 1.0, -0.5]","[[1, 1, 1], [1, 4, 5], [4, 3, 4]]"
6,La Matriz base es singular,"[[1, 1, 1], [2, 3, 4], [3, 3, 3]]"
7,"[1.0, 0.0, -0.0]","[[1, 1, 1], [2, 3, 5], [3, 3, 4]]"
8,"[1.0, 0.0, -0.0]","[[1, 1, 1], [2, 4, 5], [3, 3, 4]]"
9,"[2.0, -0.9999999999999997, -3.3306690738754706e-16]","[[1, 1, 1], [3, 4, 5], [3, 3, 4]]"

 Matriz de rango deficiente):

                     Solucion                               Base
0  La Matriz base es singular  [[1, 1, 1], [1, 2, 3], [2, 3, 4]]
1  La Matriz base es singular  [[1, 1, 1], [1, 2, 4], [2, 3, 5]]
2  La Matriz base es singular  [[1, 1, 1], [1, 2, 5], [2, 3, 6]]
3  La Matriz base es singular  [[1, 1, 1], [1, 3, 4], [2, 4, 5]]
4  La Matriz base es singular  [[1, 1, 1], [1, 3, 5], [2, 4, 6]]
5  La Matriz base es singular  [[1, 1, 1], [1, 4, 5], [2, 5, 6]]
6  La Matriz base es singular  [[1, 1, 1], [2, 3, 4], [3, 4, 5]]
7            [1.0, 0.0, -0.0]  [[1, 1, 1], [2, 3, 5], [3, 4, 6]]
8            [1.0, 0.0, -0.0]  [[1, 1, 1], [2, 4, 5], [3, 5, 6]]
9  La Matriz base es singular  [[1, 1, 1], [3, 4, 5], [4, 5, 6]]

# Segundo Punto

a)
Una planta de energía quema carbón, petróleo y gas para generar electricidad. Suponga que cada
tonelada de carbón genera 600 kilovatios hora, emite 20 unidades de bióxido de azufre y 15 unidades
de partículas suspendidas y tiene un costo de 200 dólares; cada tonelada de petróleo genera 550
kilovatios hora, emite 18 unidades de bioxido de azufre y 12 unidades de partículas suspendidas y tiene
un costo de 220 dólares; cada tonelada de gas genera 500 kilovatios hora, emite 15 unidades de bióxido de
azufre y 10 unidades de partículas suspendidas y tiene un costo de 250 dólares.
La oficina de protección ambiental restringe las emisiones diarias de bióxido de azufre a no más de 60
unidades y las partículas suspendidas a no más de 75. Si la planta de energía tiene un presupuesto para
este proyecto de 2000 dólares diarios en combustible, ¿cuánto combustible de cada clase debe comprar
para maximizar la cantidad de energía generada?

Variables de desición
$x_c$: Toneladas de carbón
$x_p$: Toneladas de petróleo
$x_g$: Toneladas de gas

Función de costo, se busca maximizar la cantidad de energía generada.

$\max  600x_c+550x_p+500x_g$ (kWh)

Restricciones del problema:

Limita la cantidad de unidades de bióxido de azufre producida por la planta de energía diariamente.

$20x_c+18x_p+15x_g\leqq 60$ (unidades de bióxido de azufre)

Limita la cantidad de unidades de partículas suspendidas producidas por la planta de energía diariamente.

$15x_c+12x_p+10x_g\leqq 75$ (unidades de partículas suspendidas)

Limita el dinero utilizado por la planta de energía diariamente.

$200x_c+220x_p+250x_g\leqq 2000$ ($)

Las variables $x_c,x_p,x_g\geqslant0$

Problema de programación lineal en forma estándar

$\min -600x_c-550x_p-500x_g$

s.a.

$20x_c+18x_p+15x_g+s_1 = 60$
$15x_c+12x_p+10x_g+s_2 = 75$
$200x_c+220x_p+250x_g+s_3 = 2000$

$x_c,x_p,x_g,s_1,s_2,s_3\geqslant0$

Problema de la forma $Ax\leqq b$ 

$\min \begin{bmatrix}
-600\\ -550\\ -500 \\
\end{bmatrix}^Tx$


$\begin{bmatrix}
20 & 18 & 15 \\
15 & 12 & 10 \\
200 & 220 & 250 \\
\end{bmatrix}x \leqq
\begin{bmatrix}
60 \\
75 \\
2000 \\
\end{bmatrix}$

In [27]:
# subpuntos B
A=[[20,18,15],[15,12,10],[200,220,250]]
b=[60,75,2000]
c=[-600,-550,-500]
A=np.array(A)
b=np.array(b)
def Puntob(A,b):
  sol = solucionesbasicas(A,b)
  solbasicas = sol['Solucion']
  costos = []
  tipo = []
  for i in solbasicas:
    es_factible = 1;
    j = 0
    while j<len(i) and es_factible == 0:
      if i[j]<0:
        es_factible = 0
        tipo.append("Básica")
      j += 1
    if es_factible == 1:
      tipo.append("Básica factible")
    costo = np.dot(np.array(c),np.array(i))
    costos.append(costo)
  m=[sol,tipo,costos]
  return m
solucion=Puntob(A,b)[0]
tipo=Puntob(A,b)[1]
costos=Puntob(A,b)[2]

TablaSolucion = pd.DataFrame(solucion)
TablaSolucion["Tipo de solución"] = tipo
TablaSolucion["Valor"] = costos

display(TablaSolucion)

,Solucion,Base,Tipo de solución,Valor
0,"[21.00000000000001, -47.50000000000003, 33.000000000000014]","[[20, 18, 15], [15, 12, 10], [200, 220, 250]]",Básica factible,-2975.0

In [34]:
#punto C.1 y 2
def TiempoSolucionfabrica(A,b): 
  start=time.time()
  solucion=Puntob(A,b)[0]
  tipo=Puntob(A,b)[1]
  costos=Puntob(A,b)[2]
  TablaSolucion = pd.DataFrame(solucion)
  TablaSolucion["Tipo de solución"] = tipo
  TablaSolucion["Valor"] = costos
  display(TablaSolucion)
  end=time.time()
  tiempo="Tiempo:"+str(end-start)
  return tiempo
def revised_simplex(A,b,c):#tiempo del metodo revised simplex con las matrices A,B y c del problema 2
  start=time.time()
  metodo=linprog(c, A_ub=A, b_ub=b, method='revised simplex', options={"disp":True})
  end=time.time()
  tiempo="Tiempo:"+str(end-start)
  return tiempo
def interior_point(A,b,c):#tiempo del metodo inferior point con las matrices A,B y c del problema 2
  start=time.time()
  metodo=linprog(c, A_ub=A, b_ub=b, method='interior-point', options={"disp":True})
  end=time.time()
  tiempo="Tiempo:"+str(end-start)
  return tiempo
def simplex(A,b,c):#tiempo del metodo simplex con las matrices A,B y c del problema 2
  start=time.time()
  metodo=linprog(c, A_ub=A, b_ub=b, method='simplex', options={"disp":True})
  end=time.time()
  tiempo="Tiempo:"+str(end-start)
  return tiempo
M=TiempoSolucionfabrica(A,b)
print(M)
M=revised_simplex(A,b,c)
print(M)
M=interior_point(A,b,c)
print(M)
M=simplex(A,b,c)
print(M)

,Solucion,Base,Tipo de solución,Valor
0,"[21.00000000000001, -47.50000000000003, 33.000000000000014]","[[20, 18, 15], [15, 12, 10], [200, 220, 250]]",Básica factible,-2975.0

Tiempo:0.013992786407470703
Phase Iteration Minimum Slack       Constraint Residual Objective
1     0         60.0                0.0                 0.0
Phase Iteration Minimum Slack       Constraint Residual Objective
2     0         60.0                0.0                 0.0
2     1         0.0                 0.0                 -1800.0
2     2         0.0                 0.0                 -2000.0
Optimization terminated successfully.
         Current function value: -2000.000000
         Iterations: 2
Tiempo:0.005005359649658203
Primal Feasibility  Dual Feasibility    Duality Gap         Step             Path Parameter      Objective
1.0                 1.0                 1.0                 -                1.0                 -1650.0
0.1654290978317     0.1654290978316     0.1654290978316     0.8371905019417  0.1654290978321     -1713.34087713
0.01254765278397    0.01254765278396    0.01254765278396    0.9449503014972  0.012547652784      -1122.691413638
0.005808161393177   0.005808161393174   0.005808161393174   0.5677940404086  0.005808161393192   -1461.533586848
0.003615256675026   0.003615256675024   0.003615256675024   0.3854444492147  0.003615256675036   -1573.978943145
0.001268680845947   0.001268680845967   0.001268680845967   0.7039191590472  0.001268680846006   -1905.6076572
1.462104790176e-05  1.462104790199e-05  1.462104790199e-05  0.9891424271159  1.462104790244e-05  -1998.197373053
7.393154833969e-10  7.39315763143e-10   7.393157609596e-10  0.9999494855139  7.393169541648e-10  -1999.999908629
3.390213727082e-14  3.679950442007e-14  3.680150315611e-14  0.9999502247742  3.696584218111e-14  -1999.999999995
Optimization terminated successfully.
         Current function value: -2000.000000
         Iterations: 8
Tiempo:0.043417930603027344
Optimization terminated successfully.
         Current function value: -2000.000000
         Iterations: 3
Tiempo:0.009549379348754883

C.3) La factibilidad se refiere a que se pueda hacer todos estos tipos de procesos en esa escala, ahora bien, cuando se menciona que la solución puede ser "No factible" a lo que se refiere es que no cumple con algunos de los limites que tienen los procesos y por tanto no se podria llevar a cabo de esta manera, por eso se debe realizar un ajuste de los parametro para que pueda ser realizada.